version: '3'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    container_name: minio.host
    hostname: minio.host
    ports:
      - 9000:9000
      - 9001:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always
    env_file: .env
    volumes:
      - ${PWD}include/minio:/data
    networks:
      - dw-e-2-e_d99a90_airflow

networks:
  dw-e-2-e_d99a90_airflow:
    external: true
    driver: bridge
